const SubServiceAPI = [
  {
     servicesName: 'psychiatric-services',
     id: 2,
     title1: "Psychiatric Services",
     title1Detail: "We offer specialized psychiatric services to address various mental health issues. Our team is well-equipped to diagnose and treat conditions such as depression, anxiety, bipolar disorder, and more.",
     img1: "/images/psychiatric-services-1.jpg",
     title2: "Medication Management",
     title2Detail: "Our psychiatrists provide ongoing medication management, ensuring that prescriptions are tailored to the patient's specific mental health needs.",
     img2: "/images/psychiatric-services-2.jpg",
     title3: "Comprehensive Assessment",
     title3Detail: "A thorough psychiatric evaluation is the cornerstone of effective treatment. We assess both medical and psychological factors.",
     img3: "/images/psychiatric-services-3.jpg",
   },
   {
     servicesName: 'psychological-services',
     id: 1,
     title1: "Psychological Services",
     title1Detail: "Our psychological services aim to enhance mental well-being through therapy, assessment, and counseling. We address a variety of emotional, behavioral, and cognitive issues.",
     img1: "/images/psychological-services-1.jpg",
     title2: "Individual Therapy",
     title2Detail: "One-on-one sessions are offered to help clients work through personal issues such as stress, trauma, or relationship problems.",
     img2: "/images/psychological-services-2.jpg",
     title3: "Family Therapy",
     title3Detail: "Family therapy addresses conflicts within family dynamics, improving communication and relationships.",
     img3: "/images/psychological-services-3.jpg",
   },
   {
     servicesName: 'speech-language-therapy',
     id: 3,
     title1: "Speech and Language Therapy",
     title1Detail: "Our speech-language therapy services help individuals improve communication skills, addressing issues like speech delays, stuttering, and articulation problems.",
     img1: "/images/speech-language-therapy-1.jpg",
     title2: "Language Development",
     title2Detail: "We provide therapy for children and adults with language delays, helping them develop functional communication skills.",
     img2: "/images/speech-language-therapy-2.jpg",
     title3: "Speech Disorders",
     title3Detail: "We treat various speech disorders, including articulation, fluency, and voice issues.",
     img3: "/images/speech-language-therapy-3.jpg",
   },
   {
     servicesName: 'career-counseling',
     id: 4,
     title1: "Career Counseling",
     title1Detail: "Our career counseling services assist individuals in making informed career decisions, providing guidance on education, job search strategies, and personal career goals.",
     img1: "/images/career-counseling-1.jpg",
     title2: "Job Search Assistance",
     title2Detail: "We help clients navigate the job market by offering resume reviews, interview preparation, and job search strategies.",
     img2: "/images/career-counseling-2.jpg",
     title3: "Career Planning",
     title3Detail: "We work with individuals to plan their career paths, aligning personal goals with job market opportunities.",
     img3: "/images/career-counseling-3.jpg",
   },
   {
     servicesName: 'rehab-services',
     id: 5,
     title1: "Rehabilitation Services",
     title1Detail: "We offer comprehensive rehabilitation services to help individuals recover from injury, surgery, or chronic conditions, with a focus on improving mobility and function.",
     img1: "/images/rehab-services-1.jpg",
     title2: "Physical Therapy",
     title2Detail: "Our physical therapy sessions are designed to improve strength, mobility, and range of motion after surgery or injury.",
     img2: "/images/rehab-services-2.jpg",
     title3: "Occupational Therapy",
     title3Detail: "Occupational therapy helps patients regain the ability to perform daily tasks and improve their quality of life.",
     img3: "/images/rehab-services-3.jpg",
   },
   {
     servicesName: 'marital-counseling',
     id: 6,
     title1: "Marital Counseling",
     title1Detail: "Our marital counseling services help couples navigate relationship challenges, improve communication, and build stronger bonds.",
     img1: "/images/marital-counseling-1.jpg",
     title2: "Conflict Resolution",
     title2Detail: "We offer strategies for conflict resolution, helping couples address underlying issues in their relationship.",
     img2: "/images/marital-counseling-2.jpg",
     title3: "Communication Skills",
     title3Detail: "Our therapists provide tools to improve communication, ensuring partners can effectively express their needs and emotions.",
     img3: "/images/marital-counseling-3.jpg",
   },
   {
     servicesName: 'treatment-psychiatric-illnesses',
     id: 7,
     title1: "Treatment for Psychiatric Illnesses",
     title1Detail: "We provide specialized treatment plans for individuals dealing with severe psychiatric illnesses, focusing on long-term recovery and quality of life.",
     img1: "/images/treatment-psychiatric-illnesses-1.jpg",
     title2: "Schizophrenia Treatment",
     title2Detail: "Our team offers comprehensive treatment for schizophrenia, including medication, therapy, and support services.",
     img2: "/images/treatment-psychiatric-illnesses-2.jpg",
     title3: "Bipolar Disorder Management",
     title3Detail: "We provide ongoing support and treatment for bipolar disorder, helping patients maintain stability and manage symptoms.",
     img3: "/images/treatment-psychiatric-illnesses-3.jpg",
   },
];

export default SubServiceAPI;
